language: java
jdk: openjdk11

env:
  - NODE_VERSION=12
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - nvm install $NODE_VERSION

before_script:
  - npm install

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
      script:
        - ./gradlew -Pprod clean bootJar
    - stage: test
      script:
        - ./gradlew test integrationTest
        - npm test
    - stage: publish
      if: repo = mbouchenoire/lowfer AND type IN (tag)
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./gradlew jib -Djib.to.image=registry.hub.docker.com/mbouchenoire/lowfer:${TRAVIS_TAG}
        - ./gradlew jib -Djib.to.image=registry.hub.docker.com/mbouchenoire/lowfer:latest
    - stage: publish
      if: repo = mbouchenoire/lowfer AND (NOT (type IN (tag)))
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./gradlew jib -Djib.to.image=registry.hub.docker.com/mbouchenoire/lowfer:${TRAVIS_BRANCH}-snapshot
